# Generated by Django 5.2.11 on 2026-09-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(help_text='One line elevator pitch of the project', max_length=255)),
                ('description', models.TextField(help_text='Full markdown description: problem statement, architecture, features, and setup guide')),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies (e.g. Django, React, PostgreSQL, Docker, Redis)', max_length=300)),
                ('category', models.CharField(choices=[('WEB', 'Web Development / Full-Stack'), ('AI_ML', 'Artificial Intelligence & ML'), ('MOBILE', 'Mobile Applications (Android / iOS / Flutter)'), ('CLOUD', 'Cloud & DevOps'), ('CYBERSEC', 'Cybersecurity & Networks'), ('BLOCKCHAIN', 'Blockchain & Web3'), ('IOT', 'Internet of Things & Embedded')], default='WEB', max_length=20)),
                ('github_url', models.URLField(blank=True, help_text='Public GitHub repository link')),
                ('live_demo_url', models.URLField(blank=True, help_text='Live hosted demo / deployment link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_looking_for_teammates', models.BooleanField(default=False)),
                ('roles_needed', models.CharField(blank=True, help_text='e.g. Frontend Developer (React), UI/UX Designer, ML Engineer', max_length=255)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_applied', models.CharField(help_text='Role you want to contribute as', max_length=150)),
                ('pitch_message', models.TextField(help_text='Why are you interested and what relevant skills/experience do you bring?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted to Team 🎉'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'applicant')},
            },
        ),
    ]
