# Generated by Django 5.2.11 on 2026-09-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='e.g. Senior SDE @ Microsoft | Ex-Amazon | Mentored 50+ MCA grads', max_length=200)),
                ('expertise_areas', models.CharField(help_text='e.g. System Design, DSA, Full-Stack, Cloud Architecture, Resume Building', max_length=300)),
                ('years_of_experience', models.PositiveIntegerField(default=3)),
                ('about', models.TextField(help_text='How you can help students and what they can expect in a 1-on-1 session')),
                ('offers_resume_review', models.BooleanField(default=True)),
                ('offers_mock_interview', models.BooleanField(default=True)),
                ('offers_career_guidance', models.BooleanField(default=True)),
                ('offers_higher_studies', models.BooleanField(default=False)),
                ('preferred_meeting_tool', models.CharField(default='Google Meet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('RESUME', 'Resume Review & Profile Optimization 📄'), ('MOCK_INTERVIEW', 'Mock Technical / HR Interview 🎯'), ('CAREER', 'Career Roadmap & Transition Advice 🚀'), ('HIGHER_STUDIES', 'Higher Studies (GATE / Ph.D / MS) 🎓'), ('PROJECT', 'Project Architecture & Code Review 💻')], default='MOCK_INTERVIEW', max_length=30)),
                ('requested_date', models.DateField(help_text='Desired date for the session')),
                ('requested_time', models.CharField(help_text='e.g. 6:00 PM - 7:00 PM IST', max_length=50)),
                ('student_notes', models.TextField(help_text='Provide context, your target company/role, or resume link')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Mentor Approval ⏳'), ('CONFIRMED', 'Confirmed & Scheduled ✅'), ('COMPLETED', 'Completed 🌟'), ('CANCELLED', 'Cancelled ❌')], default='PENDING', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting URL (Google Meet / Zoom) set by mentor upon confirmation')),
                ('mentor_notes', models.TextField(blank=True, help_text='Private or shared notes / feedback after session')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
