# Generated by Django 5.2.11 on 2026-09-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Direct URL to company logo icon')),
                ('tier', models.CharField(choices=[('TIER1', 'Tier 1 / FAANG & Big Tech'), ('TIER2', 'Product & Mid-Sized Tech'), ('SERVICE', 'IT Consulting & Services (TCS, Infosys, Wipro, etc.)'), ('STARTUP', 'High-Growth Startups')], default='TIER2', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(default='Information Technology & Software', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. SDE-1 Interview Experience at Amazon - 4 Rounds Breakdown', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('role_applied', models.CharField(help_text='e.g. Associate Software Engineer, SDE Intern, Cloud Consultant', max_length=150)),
                ('batch_year', models.PositiveIntegerField(help_text='Placement year e.g. 2025')),
                ('experience_type', models.CharField(choices=[('ON_CAMPUS', 'On-Campus Placement'), ('OFF_CAMPUS', 'Off-Campus Drive'), ('REFERRAL', 'Employee Referral'), ('INTERNSHIP', 'Internship to PPO')], default='ON_CAMPUS', max_length=20)),
                ('offer_status', models.CharField(choices=[('OFFERED', 'Accepted Offer 🎉'), ('REJECTED', 'Not Selected / Experience Shared'), ('WAITLISTED', 'Waitlisted / In Process')], default='OFFERED', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy (1/5)'), ('MEDIUM', 'Medium (3/5)'), ('HARD', 'Challenging (4/5)'), ('VERY_HARD', 'Very Tough (5/5)')], default='MEDIUM', max_length=20)),
                ('compensation_details', models.CharField(blank=True, help_text='Optional CTC range e.g. 10 - 14 LPA', max_length=100)),
                ('rounds_count', models.PositiveIntegerField(default=3, help_text='Total number of interview rounds')),
                ('summary', models.TextField(help_text='Overview of the hiring process and your preparation strategy')),
                ('rounds_breakdown', models.TextField(help_text='Detailed Markdown breakdown of each round (Round 1: OA, Round 2: Technical DSA, Round 3: System/HR)')),
                ('questions_asked', models.TextField(help_text='Specific DSA, OS, DBMS, or behavioral questions asked')),
                ('tips_for_juniors', models.TextField(help_text='Key takeaways, mistakes to avoid, and prep materials recommended')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_experiences', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='interviews.company')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interviews.interviewexperience')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
